# docker-compose.yml
version: '3.8'

services:
  deepfake-api:
    build: .
    container_name: deepfake-detection-api
    ports:
      - "8000:8000"
    volumes:
      # Mount models directory to persist weights
      - ./models:/app/models
      # Mount config
      - ./config.json:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
      # Change to 'cuda' if you have NVIDIA GPU
      - DEVICE=cpu
    restart: unless-stopped
    # Uncomment below if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Optional: Add nginx as reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: deepfake-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - deepfake-api